VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ITheme"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit

Public Function ActiveCaptionForeColor() As Long
End Function
Public Function InactiveCaptionForeColor() As Long
End Function

Public Function ActiveCaptionBackColor1() As Long
End Function
Public Function InactiveCaptionBackColor1() As Long
End Function

Public Function ActiveCaptionBackColor2() As Long
End Function
Public Function InactiveCaptionBackColor2() As Long
End Function

Public Function ActiveCaptionBackGradientAngle() As Long
End Function
Public Function InactiveCaptionBackGradientAngle() As Long
End Function

Public Function ActiveForeColor() As Long
End Function
Public Function InactiveForeColor() As Long
End Function

Public Function ActiveBackColor1() As Long
End Function
Public Function ActiveBackColor2() As Long
End Function
Public Function ActiveBackColorGradientAngle() As Long
End Function

Public Function InactiveBackColor1() As Long
End Function
Public Function InactiveBackColor2() As Long
End Function
Public Function InactiveBackColorGradientAngle() As Long
End Function


Public Function ActiveFrameColor() As Long
End Function
Public Function InactiveFrameColor() As Long
End Function

